name: CodeCheckout

on:
  workflow_dispatch:

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6