name: CodeCheckout

on:
  workflow_call:  # Reusable workflow

jobs:
  checkout:
    runs-on: Linux
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java # Set up Java environment for building the project
        uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: '17'
      
      - name: Cache Maven packages  # Cache Maven dependencies to speed up build times
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Build with Maven # Build the project using Maven
        run: mvn clean install # Stores the built artifacts in the local Maven repository for use in subsequent jobs
                               #  Also store the built artifacts in the project's target directory for use in subsequent jobs
                                 
      # - name: Maven Package # Package the project using Maven
      #   run: mvn clean package # Stores the artifacts in the projects's target directory

