name: CodeCheckout

on:
  workflow_call:

jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java # Set up Java environment for building the project
        uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: '17'
      
      - name: Cache Maven packages  # Cache Maven dependencies to speed up build times
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Build with Maven # Build the project using Maven
        run: mvn clean install