name: CI Pipeline

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs: 
  build:
    uses: ./.github/workflows/Checkout.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  sonarscan:
    needs: build
    uses: ./.github/workflows/sonar.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  testing:
    needs: sonarscan
    uses: ./.github/workflows/unit_test.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  image-build-and-push:
    needs: testing
    uses: ./.github/workflows/image-build-push.yaml
    secrets: inherit  # Inherit secrets from the calling workflow
