name: CI Pipeline

on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs: 
  
  testing:
    # needs: lint
    uses: ./.github/workflows/unit_test.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  lint:
    needs: testing
    uses: ./.github/workflows/lint.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  build:
    needs: lint
    uses: ./.github/workflows/Checkout.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  snyk-scan:
    needs: build
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  sonarscan:
    needs: build
    uses: ./.github/workflows/sonar.yaml
    secrets: inherit  # Inherit secrets from the calling workflow

  image-build-and-push:
    needs: sonarscan
    uses: ./.github/workflows/image-build-push.yaml
    secrets: inherit  # Inherit secrets from the calling workflow
