name: Sonar Run

on:
  workflow_call:

jobs:
  sonar:
    runs-on: Linux
    steps:
      # - name: checkout code
      #   uses: actions/checkout@v6

    #   - name: MVN Package
    #     run: mvn clean package

      # - name: Setup Java # Set up Java environment for building the project
      #   uses: actions/setup-java@v3
      #   with:
      #       distribution: 'adopt'
      #       java-version: '17'
    
      - name: Run SonarQube analysis
        # uses: SonarSource/sonarqube-scan-action@v7.0.0
        run: | 
            mvn sonar:sonar -Dsonar.projectKey=DevSecOps_Pipeline -Dsonar.organization=iam-manzoor -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        # with:
        #   args: >
        #     -Dsonar.projectKey=DevSecOps_Pipeline
        #     -Dsonar.organization=iam-manzoor
        #     -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
        #     -Dsonar.login=${{ secrets.SONAR_TOKEN }}