name: Testing

on: 
  workflow_call:  # Reusable workflow

jobs:
  testing:
    runs-on: Linux
    #needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java # Set up Java environment for building the project
        uses: actions/setup-java@v3
        with:
            distribution: 'adopt'
            java-version: '17'

      - name: Run unit tests # Run unit tests using Maven
        run: mvn test