name: Testing

on: 
  workflow_call:  # Reusable workflow

jobs:
  testing:
    runs-on: ubuntu-latest
    #needs: checkout
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v6

      - name: Run unit tests # Run unit tests using Maven
        run: mvn test